### ISSUE TITLE
Error in Python 2.7.9

### ISSUE THREAD

**Issue by Wilbeibi** [gleitz/howdoi#114]
when use `-c` option:
Traceback (most recent call last):
  File "/usr/local/bin/howdoi", line 9, in <module>
    load_entry_point('howdoi==1.1.7', 'console_scripts', 'howdoi')()
  File "/usr/local/lib/python2.7/site-packages/howdoi/howdoi.py", line 254, in command_line_runner
    print(howdoi(args).encode('utf-8', 'ignore'))
  File "/usr/local/lib/python2.7/site-packages/howdoi/howdoi.py", line 208, in howdoi
    return get_instructions(args) or 'Sorry, couldn\'t find any help with that topic\n'
  File "/usr/local/lib/python2.7/site-packages/howdoi/howdoi.py", line 184, in get_instructions
    answer = get_answer(args, links)
  File "/usr/local/lib/python2.7/site-packages/howdoi/howdoi.py", line 166, in get_answer
    text = format_output(instructions.eq(0).text(), args)
  File "/usr/local/lib/python2.7/site-packages/howdoi/howdoi.py", line 125, in format_output
    lexer = get_lexer_by_name(keyword)
  File "/usr/local/lib/python2.7/site-packages/pygments/lexers/__init__.py", line 90, in get_lexer_by_name
    for cls in find_plugin_lexers():
  File "/usr/local/lib/python2.7/site-packages/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/__init__.py", line 3, in <module>
    from .exporters import *
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/exporters/__init__.py", line 1, in <module>
    from .export import *
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/exporters/export.py", line 8, in <module>
    from IPython.nbformat import NotebookNode
  File "/usr/local/lib/python2.7/site-packages/IPython/nbformat/__init__.py", line 29, in <module>
    from .validator import validate, ValidationError
  File "/usr/local/lib/python2.7/site-packages/IPython/nbformat/validator.py", line 21, in <module>
    raise ImportError(str(e) + verbose_msg)
ImportError: No module named jsonschema

    IPython notebook format depends on the jsonschema package:
    
        https://pypi.python.org/pypi/jsonschema
    
    Please install it first.

upgrade `ipython` solved this problem.

**Comment by gleitz** [comment]
I think the notebook now requires jsonschema. Install it from pip or similar with `pip install jsonschema`.
