### ISSUE TITLE
TypeError (Windows 8.1, python 3.4.3)

### ISSUE THREAD

**Issue by Epskampie** [gleitz/howdoi#115]
The program doesn't seem to work on python 3.4.3, both windows 8.1 and ubuntu 14.10. Details:

* Python 3.4.3
* Installed lxml‑3.4.3‑cp34‑none‑win32.whl from http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml on windows
* apt-get install python3-lxml on linux
* Installed with pip install howdoi

```
Traceback (most recent call last):
  File "d:\Programs\python_3.4.3\Scripts\howdoi-script.py", line 9, in <module>
    load_entry_point('howdoi==1.1.7', 'console_scripts', 'howdoi')()
  File "D:\Programs\python_3.4.3\lib\site-packages\howdoi\howdoi.py", line 256, in command_line_runner
    print(howdoi(args))
  File "D:\Programs\python_3.4.3\lib\site-packages\howdoi\howdoi.py", line 208, in howdoi
    return get_instructions(args) or 'Sorry, couldn\'t find any help with that topic\n'
  File "D:\Programs\python_3.4.3\lib\site-packages\howdoi\howdoi.py", line 174, in get_instructions
    links = get_links(args['query'])
  File "D:\Programs\python_3.4.3\lib\site-packages\howdoi\howdoi.py", line 98, in get_links
    result = get_result(SEARCH_URL.format(URL, url_quote(query)))
  File "D:\Programs\python_3.4.3\lib\site-packages\howdoi\howdoi.py", line 86, in get_result
    return requests.get(url, headers={'User-Agent': random.choice(USER_AGENTS)}, proxies=get_proxies()).text
  File "D:\Programs\python_3.4.3\lib\site-packages\requests\api.py", line 68, in get
    return request('get', url, **kwargs)
  File "D:\Programs\python_3.4.3\lib\site-packages\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "D:\Programs\python_3.4.3\lib\site-packages\requests_cache\core.py", line 115, in request
    **kwargs
  File "D:\Programs\python_3.4.3\lib\site-packages\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Programs\python_3.4.3\lib\site-packages\requests_cache\core.py", line 98, in send
    return send_request_and_cache_response()
  File "D:\Programs\python_3.4.3\lib\site-packages\requests_cache\core.py", line 90, in send_request_and_cache_response
    response = super(CachedSession, self).send(request, **kwargs)
  File "D:\Programs\python_3.4.3\lib\site-packages\requests\sessions.py", line 594, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "D:\Programs\python_3.4.3\lib\site-packages\requests\sessions.py", line 594, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "D:\Programs\python_3.4.3\lib\site-packages\requests\sessions.py", line 196, in resolve_redirects
    **adapter_kwargs
  File "D:\Programs\python_3.4.3\lib\site-packages\requests_cache\core.py", line 98, in send
    return send_request_and_cache_response()
  File "D:\Programs\python_3.4.3\lib\site-packages\requests_cache\core.py", line 92, in send_request_and_cache_response
    self.cache.save_response(cache_key, response)
  File "D:\Programs\python_3.4.3\lib\site-packages\requests_cache\backends\base.py", line 45, in save_response
    self.responses[key] = self.reduce_response(response), datetime.utcnow()
  File "D:\Programs\python_3.4.3\lib\site-packages\requests_cache\backends\storage\dbdict.py", line 168, in __setitem__
    sqlite.Binary(pickle.dumps(item)))
TypeError: cannot serialize '_io.BufferedReader' object
```

It seems to be an issue in the request-cache package. I deleted the cache file, no effect. I also disabled caching in howdoi.py, this resulted in a new error, "Sorry, couldn't find any help with that topic".

**Comment by dkasak** [comment]
Same thing happening for me on Arch Linux, also Python 3.4.3.

**Comment by gleitz** [comment]
Please open this issue with [requests-cache](https://github.com/reclosedev/requests-cache/issues) and then re-open when you have an update.
