### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by anweshknayak** [gleitz/howdoi#123]
Traceback (most recent call last):
  File "/usr/local/bin/howdoi", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: request

**Comment by moribellamy** [comment]
try

    wget https://raw.githubusercontent.com/gleitz/howdoi/master/requirements.txt
    sudo pip install -r requirements.txt
