### ISSUE TITLE
ClassNotFound Exception

### ISSUE THREAD

**Issue by simonvoelcker** [gleitz/howdoi#125]
Loving this tool. However, I managed to crash it:

```
user@desktop:~$ howdoi -c -n 5 resize images in directory
Traceback (most recent call last):
  File "/usr/local/bin/howdoi", line 9, in <module>
    load_entry_point('howdoi==1.1.7', 'console_scripts', 'howdoi')()
  File "/usr/local/lib/python2.7/dist-packages/howdoi/howdoi.py", line 254, in command_line_runner
    print(howdoi(args).encode('utf-8', 'ignore'))
  File "/usr/local/lib/python2.7/dist-packages/howdoi/howdoi.py", line 208, in howdoi
    return get_instructions(args) or 'Sorry, couldn\'t find any help with that topic\n'
  File "/usr/local/lib/python2.7/dist-packages/howdoi/howdoi.py", line 184, in get_instructions
    answer = get_answer(args, links)
  File "/usr/local/lib/python2.7/dist-packages/howdoi/howdoi.py", line 166, in get_answer
    text = format_output(instructions.eq(0).text(), args)
  File "/usr/local/lib/python2.7/dist-packages/howdoi/howdoi.py", line 132, in format_output
    lexer = guess_lexer(code)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 252, in guess_lexer
    raise ClassNotFound('no lexer matching the text found')
pygments.util.ClassNotFound: no lexer matching the text found
```

Maybe someone can confirm this?

**Comment by SanketDG** [comment]
It does work on the latest version, properly.

**Comment by gleitz** [comment]
Sounds like you may need to install the latest version of pygments

**Comment by simonvoelcker** [comment]
Aye, will do. Thanks
