### ISSUE TITLE
TypeError in Python 2.7.10

### ISSUE THREAD

**Issue by metakermit** [gleitz/howdoi#126]
Just installed `howdoi` on Python 2.7.10 (installed via `brew` on OS X) and I got an error (seems to be related to requests).

```
(s)➜  ~  howdoi get stackoverflow answers inside a terminal
Traceback (most recent call last):
  File "/Users/kermit/.virtualenvs/s/bin/howdoi", line 11, in <module>
    sys.exit(command_line_runner())
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/howdoi/howdoi.py", line 254, in command_line_runner
    print(howdoi(args).encode('utf-8', 'ignore'))
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/howdoi/howdoi.py", line 208, in howdoi
    return get_instructions(args) or 'Sorry, couldn\'t find any help with that topic\n'
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/howdoi/howdoi.py", line 174, in get_instructions
    links = get_links(args['query'])
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/howdoi/howdoi.py", line 98, in get_links
    result = get_result(SEARCH_URL.format(URL, url_quote(query)))
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/howdoi/howdoi.py", line 86, in get_result
    return requests.get(url, headers={'User-Agent': random.choice(USER_AGENTS)}, proxies=get_proxies()).text
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/requests_cache/core.py", line 128, in request
    **kwargs
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/requests_cache/core.py", line 99, in send
    response, timestamp = self.cache.get_response_and_time(cache_key)
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/requests_cache/backends/base.py", line 69, in get_response_and_time
    if key not in self.responses:
  File "/Users/kermit/.virtualenvs/s/bin/../lib/python2.7/_abcoll.py", line 388, in __contains__
    self[key]
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/requests_cache/backends/storage/dbdict.py", line 163, in __getitem__
    return pickle.loads(bytes(super(DbPickleDict, self).__getitem__(key)))
  File "/Users/kermit/.virtualenvs/s/bin/../lib/python2.7/copy_reg.py", line 48, in _reconstructor
    obj = object.__new__(cls)
TypeError: ('object.__new__(HTTPHeaderDict) is not safe, use dict.__new__()', <function _reconstructor at 0x102d6fb18>, (<class 'requests.packages.urllib3._collections.HTTPHeaderDict'>, <type 'object'>, None))
```

Seems to work on Python 3.5.0.

```
(s3)➜  ~  howdoi get stackoverflow answers inside a terminal
$ howdoi get stackoverflow answers inside a terminal
```

**Comment by gleitz** [comment]
Try installing with `pip install howdoi` and let me know if that fixes the issue.

**Comment by metakermit** [comment]
Yes, I installed using pip and it's still happening:
```
s)➜  docs git:(master) ✗ python --version
Python 2.7.10
(s)➜  docs git:(master) ✗ pip install howdoi
Requirement already satisfied (use --upgrade to upgrade): howdoi in /Users/kermit/.virtualenvs/s/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pygments in /usr/local/lib/python2.7/site-packages (from howdoi)
Requirement already satisfied (use --upgrade to upgrade): requests-cache in /Users/kermit/.virtualenvs/s/lib/python2.7/site-packages (from howdoi)
Requirement already satisfied (use --upgrade to upgrade): requests in /Users/kermit/.virtualenvs/s/lib/python2.7/site-packages (from howdoi)
Requirement already satisfied (use --upgrade to upgrade): pyquery in /Users/kermit/.virtualenvs/s/lib/python2.7/site-packages (from howdoi)
Requirement already satisfied (use --upgrade to upgrade): lxml>=2.1 in /Users/kermit/.virtualenvs/s/lib/python2.7/site-packages (from pyquery->howdoi)
Requirement already satisfied (use --upgrade to upgrade): cssselect in /Users/kermit/.virtualenvs/s/lib/python2.7/site-packages (from pyquery->howdoi)
(s)➜  docs git:(master) ✗ howdoi get stackoverflow answers inside a terminal
Traceback (most recent call last):
  File "/Users/kermit/.virtualenvs/s/bin/howdoi", line 11, in <module>
    sys.exit(command_line_runner())
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/howdoi/howdoi.py", line 254, in command_line_runner
    print(howdoi(args).encode('utf-8', 'ignore'))
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/howdoi/howdoi.py", line 208, in howdoi
    return get_instructions(args) or 'Sorry, couldn\'t find any help with that topic\n'
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/howdoi/howdoi.py", line 174, in get_instructions
    links = get_links(args['query'])
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/howdoi/howdoi.py", line 98, in get_links
    result = get_result(SEARCH_URL.format(URL, url_quote(query)))
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/howdoi/howdoi.py", line 86, in get_result
    return requests.get(url, headers={'User-Agent': random.choice(USER_AGENTS)}, proxies=get_proxies()).text
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/requests_cache/core.py", line 128, in request
    **kwargs
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/requests_cache/core.py", line 99, in send
    response, timestamp = self.cache.get_response_and_time(cache_key)
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/requests_cache/backends/base.py", line 69, in get_response_and_time
    if key not in self.responses:
  File "/Users/kermit/.virtualenvs/s/bin/../lib/python2.7/_abcoll.py", line 388, in __contains__
    self[key]
  File "/Users/kermit/.virtualenvs/s/lib/python2.7/site-packages/requests_cache/backends/storage/dbdict.py", line 163, in __getitem__
    return pickle.loads(bytes(super(DbPickleDict, self).__getitem__(key)))
  File "/Users/kermit/.virtualenvs/s/bin/../lib/python2.7/copy_reg.py", line 48, in _reconstructor
    obj = object.__new__(cls)
TypeError: ('object.__new__(HTTPHeaderDict) is not safe, use dict.__new__()', <function _reconstructor at 0x10b1c7b18>, (<class 'requests.packages.urllib3._collections.HTTPHeaderDict'>, <type 'object'>, None))
```

**Comment by gleitz** [comment]
I just went through and upgraded some of the [package dependencies](https://github.com/gleitz/howdoi/commit/428efb29af440ddba278bab5a6e657f211da48be) including `requests-cache` where this issue seems to be occurring.

Would you mind cloning the repo, running `pip install requirements.txt`, and then running `python -m howdoi.howdoi QUERY` to see if it works?

**Comment by metakermit** [comment]
Yes, I tried it now on Python 2.7 based on your instructions and it works.
```
(howdoi) ➜  howdoi git:(master) python -m howdoi.howdoi install python
pip install some-package.whl

(howdoi) ➜  howdoi git:(master) python --version
Python 2.7.10
```
Just pip installing from PyPI (my original failure example for this issue) now also works.
```
(s)➜  howdoi git:(master) howdoi get stackoverflow answers inside a terminal
$ howdoi get stackoverflow answers inside a terminal
```
Thanks!

**Comment by clp** [comment]
I had a similar Type Error msg.  It went away after I re-installed requirements, then cleared the cache.

For the requirements, I had to use 'pip install -r requirements.txt' (add the '-r' option, different from the command shown above).
