### ISSUE TITLE
Not happy on python 3.6 

### ISSUE THREAD

**Issue by pathcl** [gleitz/howdoi#127]
How to reproduce:

> Install python 3.6
> Cry

pathcl@sid:~/src/python/exercises$ python
Python 3.6.0a0 (default:de982d8b7b15, Oct 13 2015, 18:14:33)

pathcl@sid:~$ howdoi somestuff python
Traceback (most recent call last):
  File "/home/pathcl/.pyenv/versions/3.6-dev/lib/python3.6/site-packages/restkit/__init__.py", line 9, in <module>
    from restkit.conn import Connection
  File "/home/pathcl/.pyenv/versions/3.6-dev/lib/python3.6/site-packages/restkit/conn.py", line 12, in <module>
    import cStringIO
ImportError: No module named 'cStringIO'
Traceback (most recent call last):
  File "/home/pathcl/.pyenv/versions/3.6-dev/lib/python3.6/site-packages/pyquery/__init__.py", line 9, in <module>
    import restkit
  File "/home/pathcl/.pyenv/versions/3.6-dev/lib/python3.6/site-packages/restkit/__init__.py", line 21, in <module>
    import urlparse
ImportError: No module named 'urlparse'

I tried to modify basic modules but then it goes beyond. 

pathcl@sid:~/src/python/exercises$ howdoi
Traceback (most recent call last):
  File "/home/pathcl/.pyenv/versions/3.6-dev/bin/howdoi", line 9, in <module>
    load_entry_point('howdoi==1.1.7', 'console_scripts', 'howdoi')()
  File "/home/pathcl/.pyenv/versions/3.6-dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/pathcl/.pyenv/versions/3.6-dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/home/pathcl/.pyenv/versions/3.6-dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/home/pathcl/.pyenv/versions/3.6-dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pathcl/.pyenv/versions/3.6-dev/lib/python3.6/site-packages/howdoi/howdoi.py", line 36, in <module>
    from pyquery import PyQuery as pq
  File "/home/pathcl/.pyenv/versions/3.6-dev/lib/python3.6/site-packages/pyquery/__init__.py", line 9, in <module>
    import restkit
  File "/home/pathcl/.pyenv/versions/3.6-dev/lib/python3.6/site-packages/restkit/__init__.py", line 10, in <module>
    from restkit.errors import ResourceNotFound, Unauthorized, RequestFailed,\
  File "/home/pathcl/.pyenv/versions/3.6-dev/lib/python3.6/site-packages/restkit/errors.py", line 32
    except (NameError, ValueError, KeyError), e:
                                            ^
SyntaxError: invalid syntax

**Comment by gleitz** [comment]
Seems to be an issue with `pyquery`. You may want to raise the issue with [them](https://github.com/gawel/pyquery).

That said Python 3.5 is the latest version I have tested as its the latest version Travis CI will test.
