### ISSUE TITLE
Command hangs? 

### ISSUE THREAD

**Issue by DavidAwad** [gleitz/howdoi#137]
installed using `pip3 install howdoi`

Installed on a macbook air running latest OSX El Capitan. Looks like requests is just hanging, and the command doesn't output anything. 

```shell
➜  ~  howdoi clear browser cache
^CTraceback (most recent call last):
  File "/usr/local/bin/howdoi", line 9, in <module>
    load_entry_point('howdoi==1.1.7', 'console_scripts', 'howdoi')()
  File "/usr/local/lib/python3.5/site-packages/howdoi/howdoi.py", line 256, in command_line_runner
    print(howdoi(args))
  File "/usr/local/lib/python3.5/site-packages/howdoi/howdoi.py", line 208, in howdoi
    return get_instructions(args) or 'Sorry, couldn\'t find any help with that topic\n'
  File "/usr/local/lib/python3.5/site-packages/howdoi/howdoi.py", line 184, in get_instructions
    answer = get_answer(args, links)
  File "/usr/local/lib/python3.5/site-packages/howdoi/howdoi.py", line 145, in get_answer
    page = get_result(link + '?answertab=votes')
  File "/usr/local/lib/python3.5/site-packages/howdoi/howdoi.py", line 86, in get_result
    return requests.get(url, headers={'User-Agent': random.choice(USER_AGENTS)}, proxies=get_proxies()).text
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests_cache/core.py", line 128, in request
    **kwargs
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests_cache/core.py", line 101, in send
    return send_request_and_cache_response()
  File "/usr/local/lib/python3.5/site-packages/requests_cache/core.py", line 93, in send_request_and_cache_response
    response = super(CachedSession, self).send(request, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 162, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 81, in create_connection
    sock.connect(sa)
KeyboardInterrupt
➜  ~
```

**Comment by gleitz** [comment]
Thanks for the report. I haven't experimented much with the `pip3` version. If you install with `pip` does it work?
