### ISSUE TITLE
Uncaught exception ClassNotFound

### ISSUE THREAD

**Issue by Daxda** [gleitz/howdoi#142]
Okay - I'm more than stupid.

I was pulling `howdoi` from an outdated source (pip) version 1.1.7 isn't the same as the master branch (1.1.8) here.

Sorry for the inconvenience!

# ignore the part below.

I'm not quite sure if the following is a bug or me being stupid, that said - please read on.

**What I'm working with**
Python: 2.7.11
pip: 2.1.0
pygments: 2.1.3
howdoi installed via pip

**Reproducing the problem (maybe?)**
When issuing `howdoi --color pygments` we get a nice stacktrace of an uncaught exception
pygments.util.ClassNotFound

``` python
Traceback (most recent call last):
  File "/usr/bin/howdoi", line 9, in <module>
    load_entry_point('howdoi==1.1.7', 'console_scripts', 'howdoi')()
  File "/usr/lib/python2.7/site-packages/howdoi/howdoi.py", line 254, in command_line_runner
    print(howdoi(args).encode('utf-8', 'ignore'))
  File "/usr/lib/python2.7/site-packages/howdoi/howdoi.py", line 208, in howdoi
    return get_instructions(args) or 'Sorry, couldn\'t find any help with that topic\n'
  File "/usr/lib/python2.7/site-packages/howdoi/howdoi.py", line 184, in get_instructions
    answer = get_answer(args, links)
  File "/usr/lib/python2.7/site-packages/howdoi/howdoi.py", line 166, in get_answer
    text = format_output(instructions.eq(0).text(), args)
  File "/usr/lib/python2.7/site-packages/howdoi/howdoi.py", line 132, in format_output
    lexer = guess_lexer(code)
  File "/usr/lib/python2.7/site-packages/pygments/lexers/__init__.py", line 252, in guess_lexer
    raise ClassNotFound('no lexer matching the text found')
pygments.util.ClassNotFound: no lexer matching the text found
```

As noted in issue #125 I checked my pygments version.

``` shell
daxda@arch:~$ pip show pygments
---
Metadata-Version: 2.0
Name: Pygments
Version: 2.1.3
Summary: Pygments is a syntax highlighting package written in Python.
Home-page: http://pygments.org/
Author: Georg Brandl
Author-email: georg@python.org
Installer: pip
License: BSD License
Location: /usr/lib/python2.7/site-packages
Requires: 
Classifiers:
  License :: OSI Approved :: BSD License
  Intended Audience :: Developers
  Intended Audience :: End Users/Desktop
  Intended Audience :: System Administrators
  Development Status :: 6 - Mature
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 3
  Operating System :: OS Independent
  Topic :: Text Processing :: Filters
  Topic :: Utilities
Entry-points:
  [console_scripts]
  pygmentize = pygments.cmdline:main

```

**Comment by Daxda** [comment]
Okay - I'm more than stupid.

I was pulling `howdoi` from an outdated source (pip) version 1.7.0 isn't the same as the master branch here.

Sorry for the inconvenience!
