### ISSUE TITLE
Update pypi -- was "pygments.util.ClassNotFound: no lexer matching the text found"

### ISSUE THREAD

**Issue by amigrave** [gleitz/howdoi#146]
**Edit:**

I was preparing a merge proposal then I saw it was already fixed https://github.com/amigrave/howdoi/commit/630fd0bd0b8e059279bbf3b4f0f4dc51f74faf85

A pypi update would be welcome !

---

Issuing this command:

    $ howdoi -c nes mmc3 bank switching

finds this answer:
http://stackoverflow.com/questions/3030565/bank-switching-sprites-on-old-nes-applications

And it seems the first code block of the answer confuses pygments that raises an exception:

```
Traceback (most recent call last):
  File "/usr/local/bin/howdoi", line 9, in <module>
    load_entry_point('howdoi==1.1.7', 'console_scripts', 'howdoi')()
  File "/usr/local/lib/python2.7/dist-packages/howdoi/howdoi.py", line 254, in command_line_runner
    print(howdoi(args).encode('utf-8', 'ignore'))
  File "/usr/local/lib/python2.7/dist-packages/howdoi/howdoi.py", line 208, in howdoi
    return get_instructions(args) or 'Sorry, couldn\'t find any help with that topic\n'
  File "/usr/local/lib/python2.7/dist-packages/howdoi/howdoi.py", line 184, in get_instructions
    answer = get_answer(args, links)
  File "/usr/local/lib/python2.7/dist-packages/howdoi/howdoi.py", line 166, in get_answer
    text = format_output(instructions.eq(0).text(), args)
  File "/usr/local/lib/python2.7/dist-packages/howdoi/howdoi.py", line 132, in format_output
    lexer = guess_lexer(code)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 252, in guess_lexer
    raise ClassNotFound('no lexer matching the text found')
```

**Comment by gleitz** [comment]
Fixed in 1.1.9
