### ISSUE TITLE
pygments.util.ClassNotFound

### ISSUE THREAD

**Issue by roipoussiere** [gleitz/howdoi#154]
The error `pygments.util.ClassNotFound: no lexer matching the text found` is raised on some `howdoi -c commands`. Related to #125.

I am on Ubuntu 15.10 and I have the last pygments version (2.1.3).

This error is not raised anytime, just for some `howdoi -c` commands:

`howdoi -c sort list python` works well:

```
In [1]: lst = ['Stem', 'constitute', 'Sedge', 'Eflux', 'Whim', 'Intrigue']

In [2]: sorted(lst)
Out[2]: ['Eflux', 'Intrigue', 'Sedge', 'Stem', 'Whim', 'constitute']
```

but not `howdoi -c crop imagemagick`

```
Traceback (most recent call last):
  File "/usr/local/bin/howdoi", line 9, in <module>
    load_entry_point('howdoi==1.1.7', 'console_scripts', 'howdoi')()
  File "/home/nathanael/.local/lib/python2.7/site-packages/howdoi/howdoi.py", line 254, in command_line_runner
    print(howdoi(args).encode('utf-8', 'ignore'))
  File "/home/nathanael/.local/lib/python2.7/site-packages/howdoi/howdoi.py", line 208, in howdoi
    return get_instructions(args) or 'Sorry, couldn\'t find any help with that topic\n'
  File "/home/nathanael/.local/lib/python2.7/site-packages/howdoi/howdoi.py", line 184, in get_instructions
    answer = get_answer(args, links)
  File "/home/nathanael/.local/lib/python2.7/site-packages/howdoi/howdoi.py", line 166, in get_answer
    text = format_output(instructions.eq(0).text(), args)
  File "/home/nathanael/.local/lib/python2.7/site-packages/howdoi/howdoi.py", line 132, in format_output
    lexer = guess_lexer(code)
  File "/home/nathanael/.local/lib/python2.7/site-packages/pygments/lexers/__init__.py", line 252, in guess_lexer
    raise ClassNotFound('no lexer matching the text found')
pygments.util.ClassNotFound: no lexer matching the text found
```

Note the non-pygmented result of this command is:

```
convert input.jpg -resize 100x100^ \
                  -gravity Center  \
                  -extent 100x100  \
        output.jpg
```

So obviously pygment can not guess the language.

**Comment by gleitz** [comment]
Thanks for the report. I have howdoi installed from pip (`pip install howdoi`) and am not seeing any issues with the command `howdoi -c crop imagemagick`.

Are you sure you are up to date with the latest howdoi?

**Comment by roipoussiere** [comment]
Oh, it was 1.1.7 (installed with setup.py). I updated to 1.1.9 with pip, it looks better now.
