### ISSUE TITLE
Can't Run Howdoi

### ISSUE THREAD

**Issue by mzaini30** [gleitz/howdoi#164]
After type `howdoi`, I get this error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/howdoi", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2711, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 588, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (requests 0.12.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('requests>=1.1.0'))
```

**Comment by mananpal1997** [comment]
@mzaini30 as it says VersionConflict, try upgrading the requests module
