### ISSUE TITLE
Howdoi fails to start because of SLL protocol version

### ISSUE THREAD

**Issue by graipher** [gleitz/howdoi#165]
When trying to use `howdoi` with any input, I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/howdoi", line 7, in <module>
    from howdoi.howdoi import command_line_runner
  File "/usr/local/lib/python2.7/dist-packages/howdoi/howdoi.py", line 16, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 62, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```

**Comment by gleitz** [comment]
How did you install howdoi? According to [this article](https://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue) you might need to upgrade the requests module.

**Comment by graipher** [comment]
Yes, that solved it, thanks!
