### ISSUE TITLE
Not import tree

### ISSUE THREAD

**Issue by Marcogb81** [gleitz/howdoi#188]
This is the result after use Howdoi in prompt. I reinstall lxml == 3.6.0
`Traceback (most recent call last):
  File "/usr/local/bin/howdoi", line 11, in <module>
    load_entry_point('howdoi==1.1.12', 'console_scripts', 'howdoi')()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/howdoi/howdoi.py", line 26, in <module>
    from pyquery import PyQuery as pq
  File "/usr/local/lib/python3.6/dist-packages/pyquery/__init__.py", line 7, in <module>
    from .pyquery import PyQuery  # NOQA
  File "/usr/local/lib/python3.6/dist-packages/pyquery/pyquery.py", line 10, in <module>
    from lxml import etree
ImportError: cannot import name 'etree'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/howdoi", line 11, in <module>
    load_entry_point('howdoi==1.1.12', 'console_scripts', 'howdoi')()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/howdoi/howdoi.py", line 26, in <module>
    from pyquery import PyQuery as pq
  File "/usr/local/lib/python3.6/dist-packages/pyquery/__init__.py", line 7, in <module>
    from .pyquery import PyQuery  # NOQA
  File "/usr/local/lib/python3.6/dist-packages/pyquery/pyquery.py", line 10, in <module>
    from lxml import etree
ImportError: cannot import name 'etree'
`

**Comment by Omar-Elrefaei** [comment]
imports work just fine on my machine with lxml (4.1.0)

**Comment by gleitz** [comment]
Does upgrading to lxml 4.1.0 help @Marcogb81?
