### ISSUE TITLE
I broke my setup  :-(

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [gleitz/howdoi#210]
I was trying to write a tutorial on using my GUI front-end for how do I and I managed to break my setup.  I'm 1/2 way panicking because I use this so much... but I know I've seen responsive action here in Issues before so I hope it'll get fixed and I'll be able to show other people how to use it.

This is my install:

> c:\Python\Anaconda3\Scripts>pip install --no-cache-dir howdoi
> Collecting howdoi
>   Downloading https://files.pythonhosted.org/packages/bc/21/87dd3caacaa7c372a9838de8e2a2a9640043e72f382cf1300574e78e9a86/howdoi-1.1.13.tar.gz
> Requirement already satisfied: pyquery in c:\python\anaconda3\lib\site-packages (from howdoi) (1.3.0)
> Requirement already satisfied: pygments in c:\python\anaconda3\lib\site-packages (from howdoi) (2.2.0)
> Requirement already satisfied: requests in c:\python\anaconda3\lib\site-packages (from howdoi) (2.18.4)
> Requirement already satisfied: requests-cache in c:\python\anaconda3\lib\site-packages (from howdoi) (0.4.13)
> Requirement already satisfied: cssselect>0.7.9 in c:\python\anaconda3\lib\site-packages (from pyquery->howdoi) (1.0.3)
> Requirement already satisfied: lxml>=2.1 in c:\python\anaconda3\lib\site-packages (from pyquery->howdoi) (3.8.0)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python\anaconda3\lib\site-packages (from requests->howdoi) (3.0.4)
> Requirement already satisfied: idna<2.7,>=2.5 in c:\python\anaconda3\lib\site-packages (from requests->howdoi) (2.6)
> Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\python\anaconda3\lib\site-packages (from requests->howdoi) (1.22)
> Requirement already satisfied: certifi>=2017.4.17 in c:\python\anaconda3\lib\site-packages (from requests->howdoi) (2017.7.27.1)
> Installing collected packages: howdoi
>   Running setup.py install for howdoi ... done
> Successfully installed howdoi-1.1.13
> 
> c:\Python\Anaconda3\Scripts>

Here is the error I get when I try to do a query:

> c:\python\pycharmprojects>python -m howdoi.howdoi test
> Traceback (most recent call last):
>   File "C:\Python\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\Python\Anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Python\Anaconda3\lib\site-packages\howdoi\howdoi.py", line 322, in <module>
>     command_line_runner()
>   File "C:\Python\Anaconda3\lib\site-packages\howdoi\howdoi.py", line 311, in command_line_runner
>     utf8_result = howdoi(args).encode('utf-8', 'ignore')
>   File "C:\Python\Anaconda3\lib\site-packages\howdoi\howdoi.py", line 263, in howdoi
>     return _get_instructions(args) or 'Sorry, couldn\'t find any help with that topic\n'
>   File "C:\Python\Anaconda3\lib\site-packages\howdoi\howdoi.py", line 233, in _get_instructions
>     answer = _get_answer(args, question_links)
>   File "C:\Python\Anaconda3\lib\site-packages\howdoi\howdoi.py", line 193, in _get_answer
>     text = _get_text(first_answer.find('.post-text').eq(0))
>   File "C:\Python\Anaconda3\lib\site-packages\howdoi\howdoi.py", line 102, in _get_text
>     return element.text(squash_space=False)
> TypeError: text() got an unexpected keyword argument 'squash_space'

Can you give me a hand?

By the way, my "repackaged version" is pip installed using
pip install pysimplegui-howdoi
But I'm leaving this out as I want to focus just on the plain howdoi install.

**Comment by MikeTheWatchGuy** [comment]
Here is my package list
```
c:\python\pycharmprojects>pip list
Package                            Version
---------------------------------- ------------------
admix                              0.1.dev2
alabaster                          0.7.10
altgraph                           0.16.1
anaconda-client                    1.6.5
anaconda-navigator                 1.6.8
anaconda-project                   0.8.0
appdirs                            1.4.3
argh                               0.26.2
args                               0.1.0
asn1crypto                         0.22.0
astroid                            1.5.3
astropy                            2.0.2
babel                              2.5.0
backports.shutil-get-terminal-size 1.0.0
beautifulsoup4                     4.6.0
binary                             1.0.0
bitarray                           0.8.1
bkcharts                           0.2
blaze                              0.11.3
bleach                             1.5.0
bokeh                              0.12.7
boto                               2.48.0
Bottleneck                         1.2.1
CacheControl                       0.12.3
cachetools                         2.1.0
certifi                            2017.7.27.1
cffi                               1.10.0
chardet                            3.0.4
ChatterBot                         0.8.7
chatterbot-corpus                  1.1.2
click                              6.7
clint                              0.5.1
cloudpickle                        0.4.0
clyent                             1.2.2
colorama                           0.3.9
comtypes                           1.1.2
conda                              4.3.30
conda-build                        3.0.22
conda-verify                       2.0.0
configparser                       3.5.0
contextlib2                        0.5.5
cryptography                       2.0.3
cssselect                          1.0.3
cycler                             0.10.0
Cython                             0.26.1
cytoolz                            0.8.2
dask                               0.15.2
databasetools                      0.3.13
datashape                          0.5.4
decorator                          4.1.2
dirutility                         0.2.19
distlib                            0.2.5
distributed                        1.18.3
Django                             2.0.3
docutils                           0.14
dropbox                            9.0.0
easygui                            0.98.1
easygui-qt                         0.9.3
ebaysdk                            2.1.4
entrypoints                        0.2.3
et-xmlfile                         1.0.1
Faker                              0.9.1
fastcache                          1.0.2
filelock                           2.0.12
fitz                               1.11.1
Flask                              0.12.2
Flask-Cors                         3.0.3
future                             0.16.0
gevent                             1.2.2
glob2                              0.5
Gooey                              1.0.1
google-api-core                    1.2.1
google-api-python-client           1.6.5
google-auth                        1.5.0
google-cloud-bigquery              1.4.0
google-cloud-core                  0.28.1
google-resumable-media             0.3.1
googleapis-common-protos           1.5.3
greenlet                           0.4.12
guizero                            0.5.3
h5py                               2.7.0
heapdict                           1.0.0
howdoi                             1.1.13
html5lib                           1.0.1
httplib2                           0.10.3
idna                               2.6
image                              1.5.20
imageio                            2.2.0
imagesize                          0.7.1
ipykernel                          4.6.1
ipython                            6.1.0
ipython-genutils                   0.2.0
ipywidgets                         7.0.0
isodate                            0.6.0
isort                              4.2.15
itsdangerous                       0.24
jdcal                              1.3
jedi                               0.10.2
Jinja2                             2.9.6
jsonschema                         2.6.0
jupyter-client                     5.1.0
jupyter-console                    5.2.0
jupyter-core                       4.3.0
jupyterlab                         0.27.0
jupyterlab-launcher                0.4.0
keras                              2.0.8
kiwisolver                         1.0.1
lazy-object-proxy                  1.3.1
livereload                         2.5.2
llvmlite                           0.20.0
locket                             0.2.0
lockfile                           0.12.2
looptools                          0.1.7
lxml                               3.8.0
macholib                           1.11
Markdown                           2.6.11
MarkupSafe                         1.0
mathparse                          0.1.1
matplotlib                         3.0.0
mccabe                             0.6.1
menuinst                           1.4.8
midi                               0.2.3
MIDIUtil                           1.2.1
mido                               1.2.8
mistune                            0.7.4
mpmath                             0.19
msgpack-python                     0.4.8
multipledispatch                   0.4.9
music21                            4.1.0
mxm.midifile                       1.1
mysql-connector                    2.1.6
navigator-updater                  0.1.0
nbconvert                          5.3.1
nbformat                           4.4.0
networkx                           1.11
nltk                               3.2.4
noise                              1.2.2
nose                               1.3.7
notebook                           5.0.0
Nuitka                             0.5.33
numba                              0.35.0+10.g143f70e
numexpr                            2.6.2
numpy                              1.14.0
numpydoc                           0.7.0
oauth2client                       4.1.2
oauthlib                           2.1.0
odo                                0.5.1
olefile                            0.44
opencv-python                      3.4.0.12
openpyxl                           2.4.8
packaging                          16.8
pandas                             0.20.3
pandocfilters                      1.4.2
partd                              0.3.8
path.py                            10.3.1
pathlib                            1.0.1
pathlib2                           2.3.0
pathtools                          0.1.2
patsy                              0.4.1
pdfkit                             0.6.1
pdfrw                              0.4
pdfwatermarker                     0.1.8
pefile                             2018.8.8
pep8                               1.7.0
pgnparser                          1.0
pickleshare                        0.7.4
Pillow                             5.2.0
pip                                18.0
pkginfo                            1.4.2
playsound                          1.2.2
ply                                3.10
port-for                           0.3.1
progress                           1.3
prompt-toolkit                     1.0.15
protobuf                           3.5.1
psutil                             5.4.7
py                                 1.4.34
py-midi                            1.2.5
py2exe                             0.9.2.2
pyasn1                             0.4.2
pyasn1-modules                     0.2.1
PyAutoGUI                          0.9.37
pycodestyle                        2.3.1
pycosat                            0.6.2
pycparser                          2.18
pycrypto                           2.6.1
pycurl                             7.43.0
pydf                               12
pyflakes                           1.5.0
pygame                             1.9.3
Pygments                           2.2.0
PyInstaller                        3.4
pylint                             1.7.2
pymongo                            3.7.1
Pympler                            0.5
PyMsgBox                           1.0.6
PyMuPDF                            1.13.16
pyodbc                             4.0.17
PyOpenGL                           3.1.0
pyOpenSSL                          17.2.0
pyparsing                          2.2.0
PyPDF2                             1.26.0
pyping                             0.0.4
pypng                              0.0.18
Pypubsub                           4.0.0
PyQRCode                           1.2.1
pyquery                            1.3.0
PyScreeze                          0.1.18
pyserial                           3.4
PySimpleGUI                        3.9.3
PySimpleGUI27                      1.1.3
PySocks                            1.6.7
pytest                             3.2.1
python-chess                       0.23.9
python-dateutil                    2.6.1
python-pdf                         0.36
python-rtmidi                      1.1.0
python-twitter                     3.4.2
pytube                             9.1.0
PyTweening                         1.0.3
pytz                               2017.2
PyWavelets                         0.5.2
pywin32                            221
pywin32-ctypes                     0.2.0
PyYAML                             3.12
pyzbar                             0.1.4
pyzmq                              16.0.2
qrcode                             5.3
qrtools                            0.0.2
QtAwesome                          0.4.4
qtconsole                          4.3.1
QtPy                               1.3.1
reedsolo                           0.3
reportlab                          3.5.2
requests                           2.18.4
requests-cache                     0.4.13
requests-oauthlib                  1.0.0
requests-toolbelt                  0.8.0
retrying                           1.3.3
rope                               0.10.5
rsa                                3.4.2
rtmidi                             2.3.3
ruamel-yaml                        0.11.14
scikit-image                       0.13.0
scikit-learn                       0.19.0
scipy                              0.19.1
seaborn                            0.8
seqseek                            0.3.3
setuptools                         40.4.3
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.11.0
snowballstemmer                    1.2.1
sortedcollections                  0.5.3
sortedcontainers                   1.5.7
Sphinx                             1.7.6
sphinx-autobuild                   0.7.1
sphinxcontrib-websupport           1.0.1
spyder                             3.2.3
SQLAlchemy                         1.2.11
statsmodels                        0.8.0
style                              1.1.0
sympy                              1.1.1
tables                             3.4.2
tblib                              1.3.2
tensorflow                         1.4.0
tensorflow-gpu                     1.4.0
tensorflow-tensorboard             0.4.0rc3
testpath                           0.3.1
text-unidecode                     1.2
tinydb                             3.10.0
tinyrecord                         0.1.5
toolz                              0.8.2
tornado                            4.5.2
tqdm                               4.19.2
traitlets                          4.3.2
twine                              1.11.0
typing                             3.6.2
unicodecsv                         0.14.1
update                             0.0.1
uritemplate                        3.0.0
urllib3                            1.22
watchdog                           0.8.3
wcwidth                            0.1.7
webencodings                       0.5.1
Werkzeug                           0.14.1
wheel                              0.32.1
widgetsnbextension                 3.0.2
win-inet-pton                      1.0.1
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.10.11
wxPython                           4.0.3
xlrd                               1.1.0
XlsxWriter                         0.9.8
xlwings                            0.11.4
xlwt                               1.3.0
youtube-dl                         2018.1.14
zict                               0.1.2
zope.interface                     4.5.0
zxing                              0.9.1
```

**Comment by MikeTheWatchGuy** [comment]
Aha!  I found this issue when I googled...

https://github.com/gleitz/howdoi/issues/192

I upgraded my pyquery and it fixed it.

Should I add something to my installer?
