### ISSUE TITLE
installation fails due to missing dependencies

### ISSUE THREAD

**Issue by Almenon** [gleitz/howdoi#242]
you have cachelib and appdirs in requirements but not in setup. This causes a failure when running howdoi due to the missing libraries.

For example:
```
F:\fifteen5>howdoi eat a apple
Traceback (most recent call last):
  File "C:\Users\almenon\AppData\Local\Programs\Python\Python36\Scripts\howdoi-script.py", line 8, in <module>
    from howdoi.howdoi import command_line_runner
  File "c:\users\almenon\appdata\local\programs\python\python36\lib\site-packages\howdoi\howdoi.py", line 18, in <module>
    from cachelib import FileSystemCache, NullCache
ModuleNotFoundError: No module named 'cachelib'
```

And in WSL:

```
almenon@DESKTOP-AE53KE4:~/work/fifteen5$ howdoi eat a apple
Traceback (most recent call last):
  File "/home/almenon/.local/bin/howdoi", line 6, in <module>
    from howdoi.howdoi import command_line_runner
  File "/home/almenon/.local/lib/python3.7/site-packages/howdoi/howdoi.py", line 16, in <module>
    import appdirs
ModuleNotFoundError: No module named 'appdirs'
```

**Comment by gleitz** [comment]
Interesting...how did you install? It worked for me with `pip` but not with `brew`.

**Comment by gleitz** [comment]
Looking at the requirements we have:

```
Pygments==2.2.0
argparse==1.4.0
cssselect==1.0.3
lxml==4.2.5
pyquery==1.4.0
requests==2.20.1
cachelib==0.1
appdirs==1.4.3
```

I assume all of these should be mirrored in setup.py?

**Comment by Almenon** [comment]
I installed with pip

**Comment by Almenon** [comment]
And yeah I would assume all those reqs should be in setup.py.  I'm not setup expert though.

**Comment by gleitz** [comment]
Try a reinstall now? I did https://github.com/gleitz/howdoi/commit/7b8b93926743efedc00867300f1b5fcfa73625e5 and pushed v1.2.1

**Comment by Almenon** [comment]
It works now, thanks!
