### ISSUE TITLE
how to use howdoi

### ISSUE THREAD

**Issue by jingkai1** [gleitz/howdoi#304]
In my using, when I print"  howdoi print stack trace python" , this terminal is stop, until I click ctrl-c.

________________________________________________________________________________
When clicking "ctrl-c", screen appear the following.

^CTraceback (most recent call last):
  File "/home/newman/.local/lib/python3.6/site-packages/howdoi/howdoi.py", line 552, in howdoi
    res = _get_answers(args)
  File "/home/newman/.local/lib/python3.6/site-packages/howdoi/howdoi.py", line 371, in _get_answers
    question_links = _get_links_with_cache(args['query'])
  File "/home/newman/.local/lib/python3.6/site-packages/howdoi/howdoi.py", line 350, in _get_links_with_cache
    links = _get_links(query)
  File "/home/newman/.local/lib/python3.6/site-packages/howdoi/howdoi.py", line 246, in _get_links
    result = _get_result(search_url.format(URL, url_quote(query)))
  File "/home/newman/.local/lib/python3.6/site-packages/howdoi/howdoi.py", line 169, in _get_result
    verify=VERIFY_SSL_CERTIFICATE).text
  File "/home/newman/.local/lib/python3.6/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/home/newman/.local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/newman/.local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/newman/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/newman/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/newman/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/newman/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/newman/.local/lib/python3.6/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/newman/.local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/newman/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/newman/.local/bin/howdoi", line 11, in <module>
    sys.exit(command_line_runner())
  File "/home/newman/.local/lib/python3.6/site-packages/howdoi/howdoi.py", line 663, in command_line_runner
    utf8_result = howdoi(args).encode('utf-8', 'ignore')
  File "/home/newman/.local/lib/python3.6/site-packages/howdoi/howdoi.py", line 559, in howdoi
    return _parse_cmd(args, res)
  File "/home/newman/.local/lib/python3.6/site-packages/howdoi/howdoi.py", line 521, in _parse_cmd
    answer = _format_answers(res, args)
  File "/home/newman/.local/lib/python3.6/site-packages/howdoi/howdoi.py", line 411, in _format_answers
    if "error" in res:
TypeError: argument of type 'NoneType' is not iterable

**Comment by jingkai1** [comment]
howdoi --version 
2.0.3

**Comment by jingkai1** [comment]
uname -a
Linux newPeople 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gleitz** [comment]
Is it possible that Google is blocked for you? I've seen that be an issue in the past. 

You might try clearing the howdoi cache, or using the command line flag for Bing search instead.

**Comment by jingkai1** [comment]
howdoi --engine bing print stack trace python


Sorry, couldn't find any help with that topic

**Comment by jingkai1** [comment]
howdoi --engine duckduckgo print hello world in python
Sorry, couldn't find any help with that topic

**Comment by gleitz** [comment]
That is certainly odd. Let me know if you figure it out.

**Comment by gleitz** [comment]
Hi,

I made a [commit](https://github.com/gleitz/howdoi/commit/5ae47b877455966fd62626e10a7ce6caaffaa8d8?w=1) to the branch `hotfix/network-error` with better handling of network and SSL errors. Would you mind trying this version locally and letting me know if you get a better error message that might help diagnose the problem?

```
git clone https://github.com/gleitz/howdoi.git
cd howdoi
git checkout hotfix/network-error
python -m howdoi.howdoi format date bash
```

**Comment by jingkai1** [comment]
$ python3 -m howdoi.howdoi format date bash
^CTraceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/newman/howdoi/howdoi/howdoi.py", line 675, in <module>
    command_line_runner()
  File "/home/newman/howdoi/howdoi/howdoi.py", line 664, in command_line_runner
    utf8_result = howdoi(args).encode('utf-8', 'ignore')
  File "/home/newman/howdoi/howdoi/howdoi.py", line 552, in howdoi
    res = _get_answers(args)
  File "/home/newman/howdoi/howdoi/howdoi.py", line 371, in _get_answers
    question_links = _get_links_with_cache(args['query'])
  File "/home/newman/howdoi/howdoi/howdoi.py", line 350, in _get_links_with_cache
    links = _get_links(query)
  File "/home/newman/howdoi/howdoi/howdoi.py", line 246, in _get_links
    result = _get_result(search_url.format(URL, url_quote(query)))
  File "/home/newman/howdoi/howdoi/howdoi.py", line 169, in _get_result
    verify=VERIFY_SSL_CERTIFICATE).text
  File "/home/newman/.local/lib/python3.6/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/home/newman/.local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/newman/.local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/newman/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/newman/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/newman/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/newman/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/newman/.local/lib/python3.6/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/newman/.local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/newman/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
KeyboardInterrupt

**Comment by jingkai1** [comment]
It is suspending when input it. until ctrl-c ,screen print this.

**Comment by gleitz** [comment]
Thanks. How weird. The only sites that are hit are google.com and stackoverflow.com. As long as those load you should be fine. 

I wonder if you might need to use a proxy server. Does the same problem happen if you get on a different wifi?

**Comment by gleitz** [comment]
Check out https://github.com/gleitz/howdoi/issues/305#issuecomment-673220957

You may need to use a VPN to get howdoi to work.

**Comment by gleitz** [comment]
In China, you may need to use a VPN to access Google, and therefore make howdoi work
