### ISSUE TITLE
I install 'howdoi' successfully,but can't make it work

### ISSUE THREAD

**Issue by tonyTn** [gleitz/howdoi#305]
some errors happened when I search something that I want

Traceback (most recent call last):
  File "/usr/local/bin/howdoi", line 8, in <module>
    sys.exit(command_line_runner())
  File "/usr/local/lib/python3.8/site-packages/howdoi/howdoi.py", line 663, in command_line_runner
    utf8_result = howdoi(args).encode('utf-8', 'ignore')
  File "/usr/local/lib/python3.8/site-packages/howdoi/howdoi.py", line 559, in howdoi
    return _parse_cmd(args, res)
  File "/usr/local/lib/python3.8/site-packages/howdoi/howdoi.py", line 521, in _parse_cmd
    answer = _format_answers(res, args)
  File "/usr/local/lib/python3.8/site-packages/howdoi/howdoi.py", line 411, in _format_answers
    if "error" in res:
TypeError: argument of type 'NoneType' is not iterable

I use a macos system 10.15.5

**Comment by gleitz** [comment]
Does this happen all the time? What were you searching for?

**Comment by gleitz** [comment]
Hi,

I made a [commit](https://github.com/gleitz/howdoi/commit/5ae47b877455966fd62626e10a7ce6caaffaa8d8?w=1) to the branch `hotfix/network-error` with better handling of network and SSL errors. Would you mind trying this version locally and letting me know if you get a better error message that might help diagnose the problem?

```
git clone https://github.com/gleitz/howdoi.git
cd howdoi
git checkout hotfix/network-error
python -m howdoi.howdoi format date bash
```

**Comment by tonyTn** [comment]
the error happened when I searched anything yesterday
maybe then environment can‘t support。
python 3.8
pip 20.2.2 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
I'll try it right now and get a better error message and help you diagnose the problem. 
thank you, gleitz!

**Comment by tonyTn** [comment]
I am not the only one who has encountered this problem。
My friends meet it too.
we tried to modify howdoi.py file line 144,It still doesn't work

**Comment by tonyTn** [comment]
hello, gleitz
I has run the "python -m howdoi.howdoi format date bash".

this is the errors:
mac@laonian howdoi % python -m howdoi.howdoi format date bash
[ERROR] Failed to establish network connection
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x10e27b5e0>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: /search?q=site:stackoverflow.com%20format%20date%20bash&hl=en (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10e27b5e0>: Failed to establish a new connection: [Errno 60] Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/mac/howdoi/howdoi/howdoi.py", line 675, in <module>
    command_line_runner()
  File "/Users/mac/howdoi/howdoi/howdoi.py", line 664, in command_line_runner
    utf8_result = howdoi(args).encode('utf-8', 'ignore')
  File "/Users/mac/howdoi/howdoi/howdoi.py", line 558, in howdoi
    raise error
  File "/Users/mac/howdoi/howdoi/howdoi.py", line 552, in howdoi
    res = _get_answers(args)
  File "/Users/mac/howdoi/howdoi/howdoi.py", line 371, in _get_answers
    question_links = _get_links_with_cache(args['query'])
  File "/Users/mac/howdoi/howdoi/howdoi.py", line 350, in _get_links_with_cache
    links = _get_links(query)
  File "/Users/mac/howdoi/howdoi/howdoi.py", line 246, in _get_links
    result = _get_result(search_url.format(URL, url_quote(query)))
  File "/Users/mac/howdoi/howdoi/howdoi.py", line 167, in _get_result
    return howdoi_session.get(url, headers={'User-Agent': _random_choice(USER_AGENTS)},
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: /search?q=site:stackoverflow.com%20format%20date%20bash&hl=en (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10e27b5e0>: Failed to establish a new connection: [Errno 60] Operation timed out'))
mac@laonian howdoi %

**Comment by tonyTn** [comment]
I'm really sorry!
I has resolved it by vpn
I am in china，the network has some problem
I'm terribly sorry to trouble you.


mac@laonian howdoi % howdoi print hellow world in java
d:>mkdir main
d:>move Hello.java main
d:>javac main\Hello.java
d:>java main.Hello
mac@laonian howdoi %

**Comment by gleitz** [comment]
Thanks for the update. I'll add something about it to the README. What VPN did you use, so I can suggest it to others?

**Comment by tonyTn** [comment]
I can't visit google if I have no one vpn named suying.

**Comment by jingkai1** [comment]
I am in china. I have a v2ray proxy. but I don't use howdoi . 

http_proxy:socks5://127.0.0.1:1080
https_proxy:socks5://127.0.0.1:1080
git_http_proxy:socks5://127.0.0.1:1080
git_https_proxy:socks5://127.0.0.1:1080

~$ python3 -m howdoi.howdoi format date bash
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/newman/.local/lib/python3.6/site-packages/howdoi/howdoi.py", line 674, in <module>
    command_line_runner()
  File "/home/newman/.local/lib/python3.6/site-packages/howdoi/howdoi.py", line 663, in command_line_runner
    utf8_result = howdoi(args).encode('utf-8', 'ignore')
  File "/home/newman/.local/lib/python3.6/site-packages/howdoi/howdoi.py", line 559, in howdoi
    return _parse_cmd(args, res)
  File "/home/newman/.local/lib/python3.6/site-packages/howdoi/howdoi.py", line 521, in _parse_cmd
    answer = _format_answers(res, args)
  File "/home/newman/.local/lib/python3.6/site-packages/howdoi/howdoi.py", line 411, in _format_answers
    if "error" in res:
TypeError: argument of type 'NoneType' is not iterable

**Comment by gleitz** [comment]
Going to close this issue for now. If you have a recommended VPN for use in China please put the instructions here and I can include it in the README
