### ISSUE TITLE
Installs OK but then cannot run

### ISSUE THREAD

**Issue by jgclark** [gleitz/howdoi#306]
Just discovered this, via ttscoff. I've installed without errors using 'python setup.py install'.
I then get this stack trace on any query:
```
howdoi -c closure ruby
Traceback (most recent call last):
  File "/usr/local/bin/howdoi", line 8, in <module>
    from howdoi.howdoi import command_line_runner
  File "build/bdist.macosx-10.15-x86_64/egg/howdoi/howdoi.py", line 125, in <module>
  File "/Library/Python/2.7/site-packages/cachelib-0.1.1-py2.7.egg/cachelib/file.py", line 54, in __init__
    self._update_count(value=len(self._list_dir()))
  File "/Library/Python/2.7/site-packages/cachelib-0.1.1-py2.7.egg/cachelib/file.py", line 69, in _update_count
    self.set(self._fs_count_file, new_count, mgmt_element=True)
  File "/Library/Python/2.7/site-packages/cachelib-0.1.1-py2.7.egg/cachelib/file.py", line 158, in set
    os.replace(tmp, filename)
AttributeError: 'module' object has no attribute 'replace'
```
Unfortunately I'm no python programmer. I'm running on macOS 10.15.6, and my version of python is 2.7.16, and it appears to be the now-deprecated version that comes bundled with macOS.  Is it a config problem? Or is it not compatible with (some) python2 systems, despite what README says?

**Comment by gleitz** [comment]
Hey, thanks for the bug report. I try my best to retain support for Python 2.7, but something slipped with the previous release. If you update howdoi with `pip install -U howdoi` you should get version 2.0.4 which supports Python 2.7.
