### ISSUE TITLE
Wierd behaviour when position(-p) is negative

### ISSUE THREAD

**Issue by aahnik** [gleitz/howdoi#321]
Please see the following results

1. `howdoi for loop python -p -1` gives this

```shell
>>> myiter = iter(range(0, 10))
>>> for i in myiter:
    print(i)
    next(myiter, None)
...
0
2
4
6
8
```

2. `howdoi for loop python -p -1000` gives

```shell
Traceback (most recent call last):
  File "/home/aahnik/Projects/how_doiBOt/venv/bin/howdoi", line 8, in <module>
    sys.exit(command_line_runner())
  File "/home/aahnik/Projects/how_doiBOt/venv/lib/python3.9/site-packages/howdoi/howdoi.py", line 672, in command_line_runner
    utf8_result = howdoi(args).encode('utf-8', 'ignore')
  File "/home/aahnik/Projects/how_doiBOt/venv/lib/python3.9/site-packages/howdoi/howdoi.py", line 560, in howdoi
    res = _get_answers(args)
  File "/home/aahnik/Projects/how_doiBOt/venv/lib/python3.9/site-packages/howdoi/howdoi.py", line 390, in _get_answers
    link = get_link_at_pos(question_links, current_position)
  File "/home/aahnik/Projects/how_doiBOt/venv/lib/python3.9/site-packages/howdoi/howdoi.py", line 262, in get_link_at_pos
    link = links[position - 1]
IndexError: list index out of range
```

**Comment by gleitz** [comment]
Thanks for the bug report. Addressed in https://github.com/gleitz/howdoi/pull/322.
