### ISSUE TITLE
Bug: InvalidSchema exception thrown when running howdoi

### ISSUE THREAD

**Issue by Srinivasa314** [gleitz/howdoi#346]
Steps to reproduce:
```
howdoi add two numbers
```

Traceback:
```
  File "/usr/bin/howdoi", line 12, in <module>
    sys.exit(command_line_runner())
  File "/usr/lib/python3.9/site-packages/howdoi/howdoi.py", line 717, in command_line_runner
    utf8_result = howdoi(args).encode('utf-8', 'ignore')
  File "/usr/lib/python3.9/site-packages/howdoi/howdoi.py", line 590, in howdoi
    res = _get_answers(args)
  File "/usr/lib/python3.9/site-packages/howdoi/howdoi.py", line 420, in _get_answers
    answer = _get_answer(args, question_links)
  File "/usr/lib/python3.9/site-packages/howdoi/howdoi.py", line 342, in _get_answer
    page = _get_result(link + '?answertab=votes')
  File "/usr/lib/python3.9/site-packages/howdoi/howdoi.py", line 184, in _get_result
    return howdoi_session.get(url, headers={'User-Agent': _random_choice(USER_AGENTS)},
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/url?esrc=s&amp;q=&amp;rct=j&amp;sa=U&amp;url=https://stackoverflow.com/questions/51638803/adding-two-numbers-with-using-only-one-variable-in-c/51638994&amp;ved=2ahUKEwiqpZazoIfvAhU-FTQIHUMnBPYQFjAAegQIARAB&amp;usg=AOvVaw3RDuPqdRPSft0WwS10O_py?answertab=votes'
```
Python version: Python 3.9.2

**Comment by gleitz** [comment]
Would you make sure you're on the latest version? You can check with `howdoi -v` and then upgrade with `pip install -U howdoi`

**Comment by gleitz** [comment]
If you're on the latest version feel free to re-open.

**Comment by Srinivasa314** [comment]
I am using the lastest version but I cannot reopen this since I do not have the rights.

**Comment by langdon** [comment]
I am currently on 2.0.14 (just ran an update) and am still getting this error (`howdoi bash awk`). Just in case this traceback is different and I didn't see it:

```python
Traceback (most recent call last):
  File "/usr/local/bin/howdoi", line 12, in <module>
    sys.exit(command_line_runner())
  File "/usr/local/lib/python3.9/site-packages/howdoi/howdoi.py", line 757, in command_line_runner
    utf8_result = howdoi(args).encode('utf-8', 'ignore')
  File "/usr/local/lib/python3.9/site-packages/howdoi/howdoi.py", line 571, in howdoi
    res = _get_answers(args)
  File "/usr/local/lib/python3.9/site-packages/howdoi/howdoi.py", line 421, in _get_answers
    answer = _get_answer(args, question_links)
  File "/usr/local/lib/python3.9/site-packages/howdoi/howdoi.py", line 343, in _get_answer
    page = _get_result(link + '?answertab=votes')
  File "/usr/local/lib/python3.9/site-packages/howdoi/howdoi.py", line 184, in _get_result
    return howdoi_session.get(url, headers={'User-Agent': _random_choice(USER_AGENTS)},
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 637, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 730, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/url?esrc=s&amp;q=&amp;rct=j&amp;sa=U&amp;url=https://stackoverflow.com/questions/44689972/using-awk-command-in-bash&amp;ved=2ahUKEwjChs_09qHvAhVRsp4KHTB-AVYQFjAAegQIBBAB&amp;usg=AOvVaw1DkUL9l6ANwQOnOySsfJdV?answertab=votes'
```

**Comment by gleitz** [comment]
@langdon please clear your cache with `-C` and the error should go away. This is related to https://github.com/gleitz/howdoi/issues/355 and will be fixed in a future release.
