### ISSUE TITLE
howdoi not working on Windows

### ISSUE THREAD

**Issue by misshecht** [gleitz/howdoi#352]
I am on Windows 7, 32 bit. Using Python 2.7.18.

Howdoi not working.

C:\Users\rh5623>howdoi howdoi
Traceback (most recent call last):
  File "C:\Python27\Scripts\howdoi-script.py", line 11, in <module>
    load_entry_point('howdoi==0.2', 'console_scripts', 'howdoi')()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 489, in l
oad_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2852, in
load_entry_point
    return ep.load()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2443, in
load
    return self.resolve()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2449, in
resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python27\lib\site-packages\howdoi\howdoi.py", line 18, in <module>
    from pyquery import PyQuery as pq
  File "c:\python27\lib\site-packages\pyquery\__init__.py", line 5, in <module>
    from .pyquery import PyQuery  # NOQA
  File "c:\python27\lib\site-packages\pyquery\pyquery.py", line 6, in <module>
    from urllib.parse import urlencode
ImportError: No module named parse

**Comment by gleitz** [comment]
Thanks for the bug report. This is a very old version of howdoi for Windows. How did you install it?

We currently only support Python>=3.5, so please try installing with `pip` or running with a newer version of Python.

**Comment by misshecht** [comment]
Oh. It’s because I’m still using Python2.

I was under the impression that that version so supported both Python 2 and 3, because that’s what the release notes say.

Thank you for clearing that up for me.

**Comment by gleitz** [comment]
I tried to keep Python 2 support as long as possible, but all the packages that howdoi uses started failing so I decided to pull support. I'll update the README to make that more clear.

Happy hacking!
