### ISSUE TITLE
[BUG] Program crashes if engine rejects howdoi

### ISSUE THREAD

**Issue by adbenitez** [gleitz/howdoi#363]
```
Traceback (most recent call last):                                                                                                                                     
  File "/home/adb/.venvs/py38/bin/howdoi", line 8, in <module>                                                                                                        
    sys.exit(command_line_runner())                                                                                                                                    
  File "/home/adb/.venvs/py38/lib/python3.8/site-packages/howdoi/howdoi.py", line 757, in command_line_runner
    utf8_result = howdoi(args).encode('utf-8', 'ignore')                                                                                                               
  File "/home/adb/.venvs/py38/lib/python3.8/site-packages/howdoi/howdoi.py", line 578, in howdoi                                                                      
    return _parse_cmd(args, res)                                                                                                                                       
  File "/home/adb/.venvs/py38/lib/python3.8/site-packages/howdoi/howdoi.py", line 540, in _parse_cmd                                                                  
    answer = _format_answers(args, res)                                                                                                                                
  File "/home/adb/.venvs/py38/lib/python3.8/site-packages/howdoi/howdoi.py", line 458, in _format_answers
    next_ans = answer["answer"]                                                                                                                                        
TypeError: string indices must be integers
```

**Comment by adbenitez** [comment]
I will do a PR soon
