### ISSUE TITLE
Not installable in python3.5

### ISSUE THREAD

**Issue by benatouba** [gleitz/howdoi#472]
#### What happened:
howdoi does not install with python 3.5 

#### What you expected to happen:
The documentation says that it would work with python3.5 or above

The `setup.py` includes f-strings which were introduced in python3.6. This leads to the following stacktrace:
```
Collecting howdoi
  Using cached https://files.pythonhosted.org/packages/6d/43/0e8166583575bd500c0f8f1a4ab9429af9466feb6fcdc006e88de8fd23e9/howdoi-2.0.20.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_sykpfkw/howdoi/setup.py", line 29
        'Pylint': f'pylint howdoi {local_python_files_str} --rcfile=.pylintrc'.split()}
                                                                             ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_sykpfkw/howdoi/
```

**Comment by gleitz** [comment]
Ah, I would accept a PR to fix the docs!
