### ISSUE TITLE
403 forbiddeb

### ISSUE THREAD

**Issue by intrepidsilence** [gleitz/howdoi#492]
#### What happened:
When running with any query it fails with a pool.py 403 forbidden error.

```
❯ howdoi format date bash
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.1_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.1_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/howdoi/2.0.20_6/libexec/lib/python3.12/site-packages/howdoi/howdoi.py", line 461, in _get_answer_worker
    answer = _get_answer(args, link)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/howdoi/2.0.20_6/libexec/lib/python3.12/site-packages/howdoi/howdoi.py", line 359, in _get_answer
    page = _get_result(link + '?answertab=votes')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/howdoi/2.0.20_6/libexec/lib/python3.12/site-packages/howdoi/howdoi.py", line 183, in _get_result
    resp.raise_for_status()
  File "/opt/homebrew/Cellar/howdoi/2.0.20_6/libexec/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://stackoverflow.com/questions/1401482/yyyy-mm-dd-format-date-in-shell-script?answertab=votes
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/bin/howdoi", line 8, in <module>
    sys.exit(command_line_runner())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/howdoi/2.0.20_6/libexec/lib/python3.12/site-packages/howdoi/howdoi.py", line 814, in command_line_runner
    howdoi_result = howdoi(args)
                    ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/howdoi/2.0.20_6/libexec/lib/python3.12/site-packages/howdoi/howdoi.py", line 632, in howdoi
    res = _get_answers(args)
          ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/howdoi/2.0.20_6/libexec/lib/python3.12/site-packages/howdoi/howdoi.py", line 446, in _get_answers
    answers = pool.starmap(
              ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.1_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.1_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://stackoverflow.com/questions/1401482/yyyy-mm-dd-format-date-in-shell-script?answertab=votes
```

#### What you expected to happen:
get a valid result

#### Output with `--explain`
Please provide the output of running the same command with the `--explain` flag like so

```
howdoi format date bash --explain
INFO: Version: 2.0.20
INFO: Fetching answers for query: format date bash
INFO: Using cached links
INFO: Links from stackoverflow.com found on google: 1
INFO: URL: https://stackoverflow.com/questions/1401482/yyyy-mm-dd-format-date-in-shell-script
INFO: Answers requested: 1, Starting at position: 1
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.1_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.1_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/howdoi/2.0.20_6/libexec/lib/python3.12/site-packages/howdoi/howdoi.py", line 461, in _get_answer_worker
    answer = _get_answer(args, link)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/howdoi/2.0.20_6/libexec/lib/python3.12/site-packages/howdoi/howdoi.py", line 359, in _get_answer
    page = _get_result(link + '?answertab=votes')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/howdoi/2.0.20_6/libexec/lib/python3.12/site-packages/howdoi/howdoi.py", line 183, in _get_result
    resp.raise_for_status()
  File "/opt/homebrew/Cellar/howdoi/2.0.20_6/libexec/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://stackoverflow.com/questions/1401482/yyyy-mm-dd-format-date-in-shell-script?answertab=votes
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/bin/howdoi", line 8, in <module>
    sys.exit(command_line_runner())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/howdoi/2.0.20_6/libexec/lib/python3.12/site-packages/howdoi/howdoi.py", line 814, in command_line_runner
    howdoi_result = howdoi(args)
                    ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/howdoi/2.0.20_6/libexec/lib/python3.12/site-packages/howdoi/howdoi.py", line 632, in howdoi
    res = _get_answers(args)
          ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/howdoi/2.0.20_6/libexec/lib/python3.12/site-packages/howdoi/howdoi.py", line 446, in _get_answers
    answers = pool.starmap(
              ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.1_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.1_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://stackoverflow.com/questions/1401482/yyyy-mm-dd-format-date-in-shell-script?answertab=votes
```

**Comment by renatocfrancisco** [comment]
@intrepidsilence my terminal didn't throw an error. have you tried uninstalling it? is it working now? issue solved?
![WindowsTerminal_KXbbtpCA7g](https://github.com/gleitz/howdoi/assets/56325092/6a23e190-f4f8-499a-975e-d455c742575d)

**Comment by intrepidsilence** [comment]
Seems to be working now. Not sure what changed. Thanks

**Comment by 111100001** [comment]
not working for me 
![image](https://github.com/user-attachments/assets/cad7e467-7b7b-4dec-a73e-852f6b543578)

**Comment by ognistyi** [comment]
The same error:


`# howdoi kill process
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ~~~~^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/usr/local/Cellar/howdoi/2.0.20_9/libexec/lib/python3.13/site-packages/howdoi/howdoi.py", line 461, in _get_answer_worker
    answer = _get_answer(args, link)
  File "/usr/local/Cellar/howdoi/2.0.20_9/libexec/lib/python3.13/site-packages/howdoi/howdoi.py", line 359, in _get_answer
    page = _get_result(link + '?answertab=votes')
  File "/usr/local/Cellar/howdoi/2.0.20_9/libexec/lib/python3.13/site-packages/howdoi/howdoi.py", line 183, in _get_result
    resp.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/Cellar/howdoi/2.0.20_9/libexec/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://stackoverflow.com/questions/32926740/how-to-kill-a-process-by-its-pid-on-linux?answertab=votes
"""`

**Comment by intrepidsilence** [comment]
yep, issue is back for me as well. found this - might be of help:

https://tariyekorogha.medium.com/solution-to-403-client-error-forbidden-for-url-with-python-3-180effbdb21

**Comment by intrepidsilence** [comment]
I also grabbed a debug of two sessions. The first (84) is the one from howdoi and the second (85) is just visiting the link that howdoi was trying to visit when it failed using Safari. The request and response data is broken into two files for each. Also, I hid the cookies sent from Safari in 85. Hope this helps.

[\[84\] Request - stackoverflow.com_questions_131303_how-can-i-measure-the-actual-memory-usage-of-an-application-or-process.txt](https://github.com/user-attachments/files/20024717/84.Request.-.stackoverflow.com_questions_131303_how-can-i-measure-the-actual-memory-usage-of-an-application-or-process.txt)
[\[84\] Response - stackoverflow.com_questions_131303_how-can-i-measure-the-actual-memory-usage-of-an-application-or-process.txt](https://github.com/user-attachments/files/20024716/84.Response.-.stackoverflow.com_questions_131303_how-can-i-measure-the-actual-memory-usage-of-an-application-or-process.txt)
[\[85\] Request - stackoverflow.com_questions_131303_how-can-i-measure-the-actual-memory-usage-of-an-application-or-process.txt](https://github.com/user-attachments/files/20024718/85.Request.-.stackoverflow.com_questions_131303_how-can-i-measure-the-actual-memory-usage-of-an-application-or-process.txt)
[\[85\] Response - stackoverflow.com_questions_131303_how-can-i-measure-the-actual-memory-usage-of-an-application-or-process.txt](https://github.com/user-attachments/files/20024719/85.Response.-.stackoverflow.com_questions_131303_how-can-i-measure-the-actual-memory-usage-of-an-application-or-process.txt)
