### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by FichteFoll** [gleitz/howdoi#66]
OS: Windows 7 x64

```
C:\Users>pip --version
pip 1.3.1 from c:\python33\lib\site-packages\pip-1.3.1-py3.3.egg (python 3.3)

C:\Users>python --version
Python 3.3.1
```

Note: This is the second run as my console did not capture all lines on the first try.

```
C:\Users>pip install howdoi
Downloading/unpacking howdoi
  Running setup.py egg_info for package howdoi

Requirement already satisfied (use --upgrade to upgrade): pyquery in c:\python33\lib\site-packages (from howdoi)
Requirement already satisfied (use --upgrade to upgrade): pygments in c:\python33\lib\site-packages (from howdoi)
Requirement already satisfied (use --upgrade to upgrade): requests in c:\python33\lib\site-packages (from howdoi)
Requirement already satisfied (use --upgrade to upgrade): requests-cache in c:\python33\lib\site-packages (from howdoi)
Downloading/unpacking lxml>=2.1 (from pyquery->howdoi)
  Running setup.py egg_info for package lxml
    Building lxml version 3.2.3.
    Building without Cython.
    ERROR: b'Der Befehl "xslt-config" ist entweder falsch geschrieben oder\r\nkonnte nicht gefunden werden.\r\n'
    ** make sure the development packages of libxml2 and libxslt are installed **

    Using build configuration of libxslt
    c:\Python33\lib\distutils\dist.py:257: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)

    warning: no files found matching '*.txt' under directory 'src\lxml\tests'
Downloading/unpacking cssselect (from pyquery->howdoi)
  Running setup.py egg_info for package cssselect

    no previously-included directories found matching 'docs\_build'
Installing collected packages: howdoi, lxml, cssselect
  Running setup.py install for howdoi

    Installing howdoi-script.py script to c:\Python33\Scripts
    Installing howdoi.exe script to c:\Python33\Scripts
  Running setup.py install for lxml
    Building lxml version 3.2.3.
    Building without Cython.
    ERROR: b'Der Befehl "xslt-config" ist entweder falsch geschrieben oder\r\nkonnte nicht gefunden werden.\r\n'
    ** make sure the development packages of libxml2 and libxslt are installed **

    Using build configuration of libxslt
    building 'lxml.etree' extension
    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\users\marco\appdata\local\temp\pip-build-marco\lxml\src\lxml\includes -Ic:\Python33\include -Ic:\Python33\include /Tcsrc\lxml\lxml.etree.c /Fobuild\temp.win-amd64-3.3\Release\src\lxml\lxml.etree.obj
    lxml.etree.c
    c:\users\marco\appdata\local\temp\pip-build-marco\lxml\src\lxml\includes\etree_defs.h(9) : fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "libxml/xmlversion.h": No such file or directory
    c:\Python33\lib\distutils\dist.py:257: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    error: command '"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\amd64\cl.exe"' failed with exit status 2
    Complete output from command c:\Python33\python.exe -c "import setuptools;__file__='c:\\users\\marco\\appdata\\local\\temp\\pip-build-marco\\lxml\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\marco\appdata\local\temp\pip-rpxb94-record\install-record.txt --single-version-externally-managed:
    Building lxml version 3.2.3.

Building without Cython.

ERROR: b'Der Befehl "xslt-config" ist entweder falsch geschrieben oder\r\nkonnte nicht gefunden werden.\r\n'

** make sure the development packages of libxml2 and libxslt are installed **



Using build configuration of libxslt

running install

running build

running build_py

copying src\lxml\includes\lxml-version.h -> build\lib.win-amd64-3.3\lxml\includes

running build_ext

building 'lxml.etree' extension

C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\users\marco\appdata\local\temp\pip-build-marco\lxml\src\lxml\includes -Ic:\Python33\include -Ic:\Python33\include /Tcsrc\lxml\lxml.etree.c /Fobuild\temp.win-amd64-3.3\Release\src\lxml\lxml.etree.obj

lxml.etree.c

c:\users\marco\appdata\local\temp\pip-build-marco\lxml\src\lxml\includes\etree_defs.h(9) : fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "libxml/xmlversion.h": No such file or directory

c:\Python33\lib\distutils\dist.py:257: UserWarning: Unknown distribution option: 'bugtrack_url'

  warnings.warn(msg)

error: command '"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\amd64\cl.exe"' failed with exit status 2

----------------------------------------
Command c:\Python33\python.exe -c "import setuptools;__file__='c:\\users\\marco\\appdata\\local\\temp\\pip-build-marco\\lxml\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\marco\appdata\local\temp\pip-rpxb94-record\install-record.txt --single-version-externally-managed failed with error code 1 in c:\users\marco\appdata\local\temp\pip-build-marco\lxml
Storing complete log in C:\Users\marco\pip\pip.log
```

```
C:\Users>howdoi test
Traceback (most recent call last):
  File "c:\Python33\Scripts\howdoi-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "c:\Python33\lib\site-packages\distribute-0.6.36-py3.3.egg\pkg_resources.py", line 2806, in <module>
    working_set.require(__requires__)
  File "c:\Python33\lib\site-packages\distribute-0.6.36-py3.3.egg\pkg_resources.py", line 696, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\Python33\lib\site-packages\distribute-0.6.36-py3.3.egg\pkg_resources.py", line 594, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cssselect
```

---

Do you happen to have any idea why this fails?
Looks to me that calling `xslt-config` fails, do I have to add that manually or was it just "not installed"?

**Comment by Tset-Noitamotua** [comment]
Installation on Windows 10 (64 bit) fails:

```shell
  ... 
  Building lxml version 3.5.0.
  Building without Cython.
  ERROR: 'xslt-config' is not recognized as an internal or external command,
  operable program or batch file.

  ** make sure the development packages of libxml2 and libxslt are installed **

  Using build configuration of libxslt
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-2.7
  creating build\lib.win32-2.7\lxml
  copying src\lxml\builder.py -> build\lib.win32-2.7\lxml
  copying src\lxml\cssselect.py -> build\lib.win32-2.7\lxml
  copying src\lxml\doctestcompare.py -> build\lib.win32-2.7\lxml
  copying src\lxml\ElementInclude.py -> build\lib.win32-2.7\lxml
  copying src\lxml\pyclasslookup.py -> build\lib.win32-2.7\lxml
  copying src\lxml\sax.py -> build\lib.win32-2.7\lxml
  copying src\lxml\usedoctest.py -> build\lib.win32-2.7\lxml
  copying src\lxml\_elementpath.py -> build\lib.win32-2.7\lxml
  copying src\lxml\__init__.py -> build\lib.win32-2.7\lxml
  creating build\lib.win32-2.7\lxml\includes
  copying src\lxml\includes\__init__.py -> build\lib.win32-2.7\lxml\includes
  creating build\lib.win32-2.7\lxml\html
  copying src\lxml\html\builder.py -> build\lib.win32-2.7\lxml\html
  copying src\lxml\html\clean.py -> build\lib.win32-2.7\lxml\html
  copying src\lxml\html\defs.py -> build\lib.win32-2.7\lxml\html
  copying src\lxml\html\diff.py -> build\lib.win32-2.7\lxml\html
  copying src\lxml\html\ElementSoup.py -> build\lib.win32-2.7\lxml\html
  copying src\lxml\html\formfill.py -> build\lib.win32-2.7\lxml\html
  copying src\lxml\html\html5parser.py -> build\lib.win32-2.7\lxml\html
  copying src\lxml\html\soupparser.py -> build\lib.win32-2.7\lxml\html
  copying src\lxml\html\usedoctest.py -> build\lib.win32-2.7\lxml\html
  copying src\lxml\html\_diffcommand.py -> build\lib.win32-2.7\lxml\html
  copying src\lxml\html\_html5builder.py -> build\lib.win32-2.7\lxml\html
  copying src\lxml\html\_setmixin.py -> build\lib.win32-2.7\lxml\html
  copying src\lxml\html\__init__.py -> build\lib.win32-2.7\lxml\html
  creating build\lib.win32-2.7\lxml\isoschematron
  copying src\lxml\isoschematron\__init__.py -> build\lib.win32-2.7\lxml\isoschematron
  copying src\lxml\lxml.etree.h -> build\lib.win32-2.7\lxml
  copying src\lxml\lxml.etree_api.h -> build\lib.win32-2.7\lxml
  copying src\lxml\includes\c14n.pxd -> build\lib.win32-2.7\lxml\includes
  copying src\lxml\includes\config.pxd -> build\lib.win32-2.7\lxml\includes
  copying src\lxml\includes\dtdvalid.pxd -> build\lib.win32-2.7\lxml\includes
  copying src\lxml\includes\etreepublic.pxd -> build\lib.win32-2.7\lxml\includes
  copying src\lxml\includes\htmlparser.pxd -> build\lib.win32-2.7\lxml\includes
  copying src\lxml\includes\relaxng.pxd -> build\lib.win32-2.7\lxml\includes
  copying src\lxml\includes\schematron.pxd -> build\lib.win32-2.7\lxml\includes
  copying src\lxml\includes\tree.pxd -> build\lib.win32-2.7\lxml\includes
  copying src\lxml\includes\uri.pxd -> build\lib.win32-2.7\lxml\includes
  copying src\lxml\includes\xinclude.pxd -> build\lib.win32-2.7\lxml\includes
  copying src\lxml\includes\xmlerror.pxd -> build\lib.win32-2.7\lxml\includes
  copying src\lxml\includes\xmlparser.pxd -> build\lib.win32-2.7\lxml\includes
  copying src\lxml\includes\xmlschema.pxd -> build\lib.win32-2.7\lxml\includes
  copying src\lxml\includes\xpath.pxd -> build\lib.win32-2.7\lxml\includes
  copying src\lxml\includes\xslt.pxd -> build\lib.win32-2.7\lxml\includes
  copying src\lxml\includes\etree_defs.h -> build\lib.win32-2.7\lxml\includes
  copying src\lxml\includes\lxml-version.h -> build\lib.win32-2.7\lxml\includes
  creating build\lib.win32-2.7\lxml\isoschematron\resources
  creating build\lib.win32-2.7\lxml\isoschematron\resources\rng
  copying src\lxml\isoschematron\resources\rng\iso-schematron.rng -> build\lib.win32-2.7\lxml\isoschematron\resources\rng
  creating build\lib.win32-2.7\lxml\isoschematron\resources\xsl
  copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl -> build\lib.win32-2.7\lxml\isoschematron\resources\xsl
  copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl -> build\lib.win32-2.7\lxml\isoschematron\resources\xsl
  creating build\lib.win32-2.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstract_expand.xsl -> build\lib.win32-2.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_include.xsl -> build\lib.win32-2.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_message.xsl -> build\lib.win32-2.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_skeleton_for_xslt1.xsl -> build\lib.win32-2.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for_xslt1.xsl -> build\lib.win32-2.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -> build\lib.win32-2.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat). Get it from http://aka.ms/vcpython27

  ----------------------------------------
  Failed building wheel for lxml
  Running setup.py bdist_wheel for cssselect
  Stored in directory: C:\Users\me\AppData\Local\pip\Cache\wheels\c6\0e\79\ae69bf7b31029e0f0bc5b8306547f94ec3926b7dbb8452b5ea
Successfully built howdoi pyquery requests-cache cssselect
Failed to build lxml
Installing collected packages: lxml, cssselect, pyquery, pygments, requests, requests-cache, howdoi
  Running setup.py install for lxml
    Complete output from command "c:\users\me\envs\howdoi\scripts\python.exe" -c "import setuptools, tokenize;__file__='c:\\users\\me~1\\appdata\\local\\temp\\pip-build-fo2lg0\\lxml\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\me~1\appdata\local\temp\pip-n1seda-record\install-record.txt --single-version-externally-managed --compile --install-headers "c:\users\me\envs\howdoi\include\site\python2.7\lxml":
    Building lxml version 3.5.0.
    Building without Cython.
    ERROR: 'xslt-config' is not recognized as an internal or external command,
    operable program or batch file.

    ** make sure the development packages of libxml2 and libxslt are installed **

    Using build configuration of libxslt
    running install
    running build
    running build_py
    copying src\lxml\includes\lxml-version.h -> build\lib.win32-2.7\lxml\includes
    running build_ext
    building 'lxml.etree' extension
    error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat). Get it from http://aka.ms/vcpython27

    ----------------------------------------
Command ""c:\users\me\envs\howdoi\scripts\python.exe" -c "import setuptools, tokenize;__file__='c:\\users\\me~1\\appdata\\local\\temp\\pip-build-fo2lg0\\lxml\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\me~1\appdata\local\temp\pip-n1seda-record\install-record.txt --single-version-externally-managed --compile --install-headers "c:\users\me\envs\howdoi\include\site\python2.7\lxml"" failed with error code 1 in c:\users\me~1\appdata\local\temp\pip-build-fo2lg0\lxml
```
